trigger:
  - master

pool:
  name: 'JioBuildAgent'

variables:
  - name: JAVA_HOME
    value: /home/udeploy/jdk-17.0.2

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      jdkDirectory: '/home/udeploy/jdk-17.0.2'
      javaHomeOption: 'path'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: '$(goals)'

